version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.READER_TOKEN }}
updates:
  - package-ecosystem: npm
    directory: "/"
    registries: "*"
    schedule:
      interval: weekly
      day: "monday"
      time: "06:00"
      timezone: "Europe/Oslo"
    ignore:
      - dependency-name: "vite-plugin-mock"
        update-types: ["version-update:semver-major"]
    groups:
      all-minor-updates:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Oslo"
    groups:
      all-minor-updates:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Oslo"
    groups:
      github:
        patterns:
          - "*"
