apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-up-skattekort
  namespace: okonomi
  labels:
    team: okonomi
  annotations:
    config.linkerd.io/proxy-memory-limit: "512Mi"
    config.linkerd.io/proxy-memory-request: "128Mi"
spec:
  image: "{{ image }}"
  port: 8080
  liveness:
    path: /sokos-up-skattekort/internal/isAlive
    initialDelay: 10
  readiness:
    path: /sokos-up-skattekort/internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /sokos-up-skattekort/internal/metrics
  replicas:
    min: 2
    max: 2
  ingresses:
    - "https://utbetalingsportalen.intern.nav.no/sokos-up-skattekort"
    - "https://utbetalingsportalen.ansatt.nav.no/sokos-up-skattekort"
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "50m"
      memory: 256Mi
