apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-up-skattekort
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: "{{{ image }}}"
  port: 3000
  liveness:
    path: /api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /api/internal/isReady
    initialDelay: 10
  replicas:
    min: 1
    max: 2
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          - id: "4a485519-e9aa-483a-a509-0d56816902ff" # 0000-CA-SOKOS-MF-Astro-Template
        extra:
          - NAVident
  accessPolicy:
    inbound:
      rules:
        - application: sokos-utbetalingsportalen
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 128Mi
  env:
    - name: SOKOS_SKATTEKORT_PERSON_API
      value: "https://sokos-skattekort-person"
